From 699cfe3b51130d9fdeca133c93bd3a4dcf25821d Mon Sep 17 00:00:00 2001
From: Luigi Pinca <luigipinca@gmail.com>
Date: Tue, 12 Jul 2022 22:11:10 +0200
Subject: [PATCH] test: fix test-socket-write-after-fin-error

The `'error'` event is not emitted because the socket is already
destroyed when `socket.write()` is called. Use the `socket.write()`
callback instead.
---
 test/parallel/test-socket-write-after-fin-error.js | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)

--- a/test/parallel/test-socket-write-after-fin-error.js
+++ b/test/parallel/test-socket-write-after-fin-error.js
@@ -16,10 +16,7 @@
 
 const server = net.createServer(function(sock) {
   sock.setEncoding('utf8');
-  sock.on('error', function(er) {
-    console.error(`${er.code}: ${er.message}`);
-    gotServerError = er;
-  });
+  sock.on('error', function() {});
 
   sock.on('data', function(c) {
     serverData += c;
@@ -27,7 +24,10 @@
   sock.on('end', function() {
     gotServerEnd = true;
     setImmediate(() => {
-      sock.write(serverData);
+      sock.write(serverData, function(er) {
+        console.error(`${er.code}: ${er.message}`);
+        gotServerError = er;
+      });
       sock.end();
     });
   });
--- a/test/parallel/parallel.status
+++ b/test/parallel/parallel.status
@@ -32,6 +32,9 @@
 ## fails when running with eatmydata
 test-fs-error-messages: PASS,FLAKY
 
+# https://github.com/nodejs/node/pull/42340 fails with libuv1 1.44.2
+test-tls-streamwrap-buffersize: PASS, FLAKY
+
 # this new test doesn't have a built target properly setup
 test-child-process-stdio-overlapped: SKIP
 
